apiVersion: v1
kind: Pod
metadata:
  name: pod-max-privileged
spec:
  hostNetwork: true
  hostPID: true 
  containers:
  - name: ping
    image: alpine
    securityContext:
      privileged: true
    command:
    - sleep
    - "5000"
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /

