apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: boss-psp
spec:
  privileged: true
  DefaultAddCapabilities:      
  runAsUser:  
    rule: 'RunAsAny'
  seLinux:                 
    rule: 'RunAsAny'                       
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  volumes:
  - secret
  - emptyDir
  - configMap
  - hostPath
  - persistendVolumeClaim
